#!/usr/bin/env python3
"""
8D-CP1.5 Part 3 — Review artifact generation.

Reads output/dispositions.csv, renders a human-skimmable Markdown review table
to output/review_table.md.

The Markdown is READ-ONLY. To override a disposition, edit dispositions.csv
directly, then re-run this script to refresh the Markdown.

Usage:
  python 03_render_review.py
"""

import csv
import sys
from pathlib import Path

# Windows console (cp1252) chokes on non-ASCII output — emit UTF-8 instead of crashing.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

OUTPUT_DIR = Path(__file__).parent / "output"
CONF_ORDER = {"low": 0, "medium": 1, "high": 2}


def read_dispositions():
    path = OUTPUT_DIR / "dispositions.csv"
    if not path.exists():
        print(f"ERROR: {path} not found. Run 02_classify_with_haiku.py first.")
        sys.exit(1)
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def esc(s):
    """Escape pipe chars so they don't break the Markdown table."""
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def sort_key(d):
    return (CONF_ORDER.get(d.get("confidence", "high"), 3),
            d.get("family") or "",
            (d.get("name") or "").lower())


def render_table(rows):
    out = ["| Approve? | Name | Family | Disposition | Target | Confidence | Reasoning |",
           "|---|---|---|---|---|---|---|"]
    for d in rows:
        out.append(
            f"|  | {esc(d.get('name'))} | {esc(d.get('family'))} | "
            f"{esc(d.get('disposition'))} | {esc(d.get('target_base_name'))} | "
            f"{esc(d.get('confidence'))} | {esc(d.get('reasoning'))} |"
        )
    return "\n".join(out)


def main():
    rows = read_dispositions()
    rows.sort(key=sort_key)

    by_disp, by_conf = {}, {}
    for d in rows:
        by_disp[d.get("disposition", "?")] = by_disp.get(d.get("disposition", "?"), 0) + 1
        by_conf[d.get("confidence", "?")] = by_conf.get(d.get("confidence", "?"), 0) + 1

    low = [d for d in rows if d.get("confidence") == "low"]
    new_base = [d for d in rows if d.get("disposition") in ("promote_to_base", "link_to_new_base")]
    standalone = [d for d in rows if d.get("disposition") == "standalone"]

    md = []
    md.append("# 8D-CP1.5 — Variant linkage review")
    md.append("")
    md.append("_Generated by `03_render_review.py` from `dispositions.csv`._")
    md.append("")
    md.append("## How to use this file")
    md.append("")
    md.append("This Markdown is **read-only**. To change a disposition, edit "
              "**`dispositions.csv`** (the editable source of truth), then re-run "
              "`03_render_review.py` to refresh this file.")
    md.append("")
    md.append("- **Approve a row as-is:** leave it alone.")
    md.append("- **Re-disposition a row:** edit the `disposition` column in `dispositions.csv` "
              "to one of `link_to_existing_base` / `promote_to_base` / `link_to_new_base` / "
              "`standalone`; edit `target_base_name` if needed; append `[overridden]` to "
              "`reasoning` for traceability.")
    md.append("- **Reject a row entirely:** set `disposition` to `standalone` (the safe no-op — "
              "no SQL is generated for it).")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append(f"- **Total rows:** {len(rows)}")
    md.append("- **By disposition:** " + ", ".join(f"{k}={by_disp[k]}" for k in sorted(by_disp)))
    md.append("- **By confidence:** " + ", ".join(f"{k}={by_conf.get(k, 0)}" for k in ("low", "medium", "high")))
    md.append("")
    md.append(f"## Low-confidence rows ({len(low)}) — review these first")
    md.append("")
    md.append("These are the calls Haiku was least sure about. Per the ambiguity-bias rule "
              "they should mostly be `standalone`; scan for any that look mis-linked.")
    md.append("")
    md.append(render_table(low) if low else "_None._")
    md.append("")
    md.append(f"## New-base proposals ({len(new_base)})")
    md.append("")
    md.append("Rows that create new base rows (`promote_to_base` / `link_to_new_base`). "
              "Worth a separate skim — a new base is a structural change.")
    md.append("")
    md.append(render_table(new_base) if new_base else "_None._")
    md.append("")
    md.append(f"## Standalone proposals ({len(standalone)})")
    md.append("")
    md.append("Verify Haiku did not over-bias toward `standalone`. A genuine standalone is "
              "fine; a missed link is an under-match the matcher will silently produce.")
    md.append("")
    md.append(render_table(standalone) if standalone else "_None._")
    md.append("")
    md.append(f"## All rows ({len(rows)}) — sorted by confidence, then family, then name")
    md.append("")
    md.append(render_table(rows))
    md.append("")

    out_path = OUTPUT_DIR / "review_table.md"
    out_path.write_text("\n".join(md), encoding="utf-8")
    print(f"Wrote review table → {out_path}")
    print(f"  {len(rows)} rows | low-confidence: {len(low)} | new-base: {len(new_base)} | standalone: {len(standalone)}")
    print("\nSkim review_table.md, edit dispositions.csv for overrides, then:")
    print("  python 04_generate_sql.py")


if __name__ == "__main__":
    main()
