// ============================================
// FRIGO — LOT INPUT ROW VIEW (Phase 8R-CP6e-PantryUI-c)
// ============================================
// Compact inline lot form used inside SupplyCreateSheet when tracks_lots is
// enabled at supply-create time. One row per lot the user wants to seed.
//
// Slimmer than LotEditSheet's form: the primary fields (qty, unit, storage)
// are always visible; variant + brand + notes hide behind a "+ more" disclosure
// to keep the inline form scannable. Dates default to today / blank — the
// user can refine later via LotEditSheet from SupplyDetail.
//
// `LotInputRow` shape is defined HERE because it's a UI-layer-only struct
// (Constraint 3 — no new types in lib/types/).
// Location: components/pantry/LotInputRowView.tsx
// ============================================

import { useMemo, useState } from 'react';
import {
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useTheme } from '../../lib/theme/ThemeContext';
import { borderRadius, spacing, typography } from '../../lib/theme';
import type { StorageLocation } from '../../lib/types/supplies';
import DateTimePicker from '../DateTimePicker';
import UnitPicker from '../UnitPicker';

const STORAGE_OPTIONS: StorageLocation[] = ['fridge', 'freezer', 'pantry', 'counter'];

/**
 * UI-layer-only lot input shape. Mirror of the persistable lot fields, but as
 * a form-friendly struct (numeric inputs are strings; expires_at can be null
 * meaning "let server compute default at save").
 *
 * The `id` is a local key only — not the persisted lot id. Generated by the
 * parent (SupplyCreateSheet) via crypto.randomUUID() or a fallback.
 */
export interface LotInputRow {
  id: string;
  quantity: string;
  quantity_unit: string;
  storage_location: StorageLocation;
  variant_label: string;
  brand: string;
  acquired_at: Date;
  expires_at: Date | null;
  expires_at_touched: boolean;
  notes: string;
}

export interface LotInputRowViewProps {
  row: LotInputRow;
  index: number;
  canRemove: boolean;
  disabled?: boolean;
  /**
   * CP6e-SmokeFix-SF1: ingredient_id from the supply being created. Null
   * for custom-name (T3) supplies. Passed through to UnitPicker so it loads
   * common units when an ingredient is selected, or falls back to all-units
   * mode otherwise.
   */
  ingredientId: string | null;
  onChange: (updated: Partial<LotInputRow>) => void;
  onRemove: () => void;
}

function formatDateDisplay(d: Date | null): string {
  if (!d) return 'Tap to set';
  return d.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

export default function LotInputRowView({
  row,
  index,
  canRemove,
  disabled,
  ingredientId,
  onChange,
  onRemove,
}: LotInputRowViewProps) {
  const { colors, functionalColors } = useTheme();
  const styles = useMemo(
    () => makeStyles(colors, functionalColors),
    [colors, functionalColors]
  );

  const [showMore, setShowMore] = useState(
    () =>
      row.variant_label.trim().length > 0 ||
      row.brand.trim().length > 0 ||
      row.notes.trim().length > 0
  );
  const [showAcquired, setShowAcquired] = useState(false);
  const [showExpires, setShowExpires] = useState(false);

  // Inline quantity validation — only error when user has typed something.
  const qtyNumber = parseFloat(row.quantity);
  const qtyInvalid =
    row.quantity.trim().length > 0 &&
    (!Number.isFinite(qtyNumber) || qtyNumber <= 0);

  return (
    <View style={styles.row}>
      <View style={styles.rowHeader}>
        <Text style={styles.rowTitle}>Lot {index + 1}</Text>
        <TouchableOpacity
          style={[styles.removeButton, !canRemove && styles.removeButtonDisabled]}
          onPress={onRemove}
          disabled={!canRemove || disabled}
          activeOpacity={0.7}
          accessibilityRole="button"
          accessibilityLabel={`Remove lot ${index + 1}`}
        >
          <Text
            style={[
              styles.removeButtonText,
              !canRemove && styles.removeButtonTextDisabled,
            ]}
          >
            ✕ Remove
          </Text>
        </TouchableOpacity>
      </View>

      <View style={styles.qtyUnitRow}>
        <TextInput
          style={[styles.input, styles.qtyInput]}
          keyboardType="decimal-pad"
          value={row.quantity}
          onChangeText={(v) => onChange({ quantity: v })}
          placeholder="Qty"
          placeholderTextColor={colors.text.tertiary}
          editable={!disabled}
          accessibilityLabel={`Lot ${index + 1} quantity`}
        />
        {/* CP6e-SmokeFix-SF1: free-text TextInput → UnitPicker. Null
            ingredientId (T3 custom-name supplies) routes the picker into
            all-units mode directly; non-null shows common-units first with
            the "Other units…" affordance. */}
        <View style={styles.unitPickerWrapper}>
          <UnitPicker
            ingredientId={ingredientId}
            selectedUnit={row.quantity_unit || null}
            onSelectUnit={(_unitId, displayName) =>
              onChange({ quantity_unit: displayName })
            }
            disabled={disabled}
          />
        </View>
      </View>
      {qtyInvalid && (
        <Text style={styles.fieldError}>Quantity must be greater than 0.</Text>
      )}

      <View style={styles.storageRow}>
        {STORAGE_OPTIONS.map((opt) => {
          const active = row.storage_location === opt;
          return (
            <TouchableOpacity
              key={opt}
              style={[styles.storageSegment, active && styles.storageSegmentActive]}
              onPress={() => onChange({ storage_location: opt })}
              disabled={disabled}
              activeOpacity={0.7}
              accessibilityRole="button"
              accessibilityState={{ selected: active }}
              accessibilityLabel={`Storage: ${opt}`}
            >
              <Text
                style={[
                  styles.storageSegmentText,
                  active && styles.storageSegmentTextActive,
                ]}
              >
                {opt.charAt(0).toUpperCase() + opt.slice(1)}
              </Text>
            </TouchableOpacity>
          );
        })}
      </View>

      <View style={styles.dateRow}>
        <TouchableOpacity
          style={styles.dateButton}
          onPress={() => setShowAcquired(true)}
          disabled={disabled}
          activeOpacity={0.7}
          accessibilityRole="button"
          accessibilityLabel={`Acquired: ${formatDateDisplay(row.acquired_at)}`}
        >
          <Text style={styles.dateButtonLabel}>Acquired</Text>
          <Text style={styles.dateButtonValue}>{formatDateDisplay(row.acquired_at)}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.dateButton}
          onPress={() => setShowExpires(true)}
          disabled={disabled}
          activeOpacity={0.7}
          accessibilityRole="button"
          accessibilityLabel={`Expires: ${formatDateDisplay(row.expires_at)}`}
        >
          <Text style={styles.dateButtonLabel}>Expires</Text>
          <Text style={styles.dateButtonValue}>
            {row.expires_at ? formatDateDisplay(row.expires_at) : 'Auto'}
          </Text>
        </TouchableOpacity>
      </View>

      {!showMore ? (
        <TouchableOpacity
          onPress={() => setShowMore(true)}
          disabled={disabled}
          activeOpacity={0.7}
          accessibilityRole="button"
          accessibilityLabel="Show more fields"
          style={styles.disclosureButton}
        >
          <Text style={styles.disclosureText}>+ Variant / brand / notes</Text>
        </TouchableOpacity>
      ) : (
        <View style={styles.moreFields}>
          <TextInput
            style={styles.input}
            value={row.variant_label}
            onChangeText={(v) => onChange({ variant_label: v })}
            placeholder="Variant (e.g., bone-in skin-on)"
            placeholderTextColor={colors.text.tertiary}
            autoCapitalize="none"
            editable={!disabled}
            accessibilityLabel={`Lot ${index + 1} variant`}
          />
          <TextInput
            style={styles.input}
            value={row.brand}
            onChangeText={(v) => onChange({ brand: v })}
            placeholder="Brand (optional)"
            placeholderTextColor={colors.text.tertiary}
            autoCapitalize="words"
            editable={!disabled}
            accessibilityLabel={`Lot ${index + 1} brand`}
          />
          <TextInput
            style={styles.input}
            value={row.notes}
            onChangeText={(v) => onChange({ notes: v })}
            placeholder="Notes (optional)"
            placeholderTextColor={colors.text.tertiary}
            editable={!disabled}
            accessibilityLabel={`Lot ${index + 1} notes`}
          />
        </View>
      )}

      <DateTimePicker
        visible={showAcquired}
        onClose={() => setShowAcquired(false)}
        onSelect={(d) => {
          onChange({ acquired_at: d });
          setShowAcquired(false);
        }}
        initialDate={row.acquired_at}
        mode="date"
        quickSelectPreset="past"
      />
      <DateTimePicker
        visible={showExpires}
        onClose={() => setShowExpires(false)}
        onSelect={(d) => {
          onChange({ expires_at: d, expires_at_touched: true });
          setShowExpires(false);
        }}
        initialDate={row.expires_at ?? new Date()}
        mode="date"
        quickSelectPreset="future"
      />
    </View>
  );
}

function makeStyles(
  colors: ReturnType<typeof useTheme>['colors'],
  functionalColors: ReturnType<typeof useTheme>['functionalColors']
) {
  return StyleSheet.create({
    row: {
      borderWidth: 1,
      borderColor: colors.border.light,
      borderRadius: borderRadius.md,
      padding: spacing.md,
      marginBottom: spacing.sm,
      backgroundColor: colors.background.secondary,
      gap: spacing.sm,
    },
    rowHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    rowTitle: {
      fontSize: typography.sizes.sm,
      fontWeight: typography.weights.semibold,
      color: colors.text.secondary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    removeButton: {
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    removeButtonDisabled: {
      opacity: 0.3,
    },
    removeButtonText: {
      fontSize: 12,
      color: functionalColors.error,
      fontWeight: typography.weights.medium,
    },
    removeButtonTextDisabled: {
      color: colors.text.tertiary,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border.medium,
      borderRadius: borderRadius.sm,
      paddingVertical: 8,
      paddingHorizontal: 10,
      fontSize: 14,
      color: colors.text.primary,
      backgroundColor: colors.background.card,
    },
    qtyUnitRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    qtyInput: {
      flex: 1,
    },
    // CP6e-SmokeFix-SF1: replaced the unitInput TextInput style with a flex
    // wrapper for UnitPicker. UnitPicker provides its own visual styling;
    // the wrapper just enforces the same flex weight the TextInput had.
    unitPickerWrapper: {
      flex: 1,
    },
    fieldError: {
      color: functionalColors.error,
      fontSize: 11,
      marginTop: -2,
    },
    storageRow: {
      flexDirection: 'row',
      gap: 4,
    },
    storageSegment: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: borderRadius.sm,
      borderWidth: 1,
      borderColor: colors.border.light,
      backgroundColor: colors.background.card,
      alignItems: 'center',
    },
    storageSegmentActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    storageSegmentText: {
      fontSize: 12,
      color: colors.text.secondary,
      fontWeight: typography.weights.medium,
    },
    storageSegmentTextActive: {
      color: '#ffffff',
    },
    dateRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    dateButton: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: borderRadius.sm,
      borderWidth: 1,
      borderColor: colors.border.light,
      backgroundColor: colors.background.card,
    },
    dateButtonLabel: {
      fontSize: 10,
      color: colors.text.tertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    dateButtonValue: {
      fontSize: 13,
      color: colors.text.primary,
      marginTop: 2,
    },
    disclosureButton: {
      paddingVertical: 6,
    },
    disclosureText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: typography.weights.medium,
    },
    moreFields: {
      gap: spacing.sm,
    },
  });
}
